// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1FtfiVEaAza71th5gqCJfOrI9UyO2Otk',
    appId: '1:886747534653:web:95b7fb18dacfa11640e154',
    messagingSenderId: '886747534653',
    projectId: 'q1-fileupload',
    authDomain: 'q1-fileupload.firebaseapp.com',
    storageBucket: 'q1-fileupload.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkRyPTaZ2P4wd9sJtQijxn5atVG33kJCo',
    appId: '1:886747534653:android:5c4ae9f90c9815f240e154',
    messagingSenderId: '886747534653',
    projectId: 'q1-fileupload',
    storageBucket: 'q1-fileupload.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvrgw8ZSZxP8UfHeREDZLh11-UWK3vBRA',
    appId: '1:886747534653:ios:a750b5a6b865669e40e154',
    messagingSenderId: '886747534653',
    projectId: 'q1-fileupload',
    storageBucket: 'q1-fileupload.appspot.com',
    iosBundleId: 'com.example.question1FileUploadProjectIliyasFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvrgw8ZSZxP8UfHeREDZLh11-UWK3vBRA',
    appId: '1:886747534653:ios:da95d4001608bf3f40e154',
    messagingSenderId: '886747534653',
    projectId: 'q1-fileupload',
    storageBucket: 'q1-fileupload.appspot.com',
    iosBundleId: 'com.example.question1FileUploadProjectIliyasFlutter.RunnerTests',
  );
}
